// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteByOrgApiKeysByIdData, DeleteByOrgApiKeysByIdErrors, DeleteByOrgApiKeysByIdResponses, DeleteByOrgByRepoBranchesByBranchData, DeleteByOrgByRepoBranchesByBranchErrors, DeleteByOrgByRepoBranchesByBranchResponses, DeleteByOrgByRepoData, DeleteByOrgByRepoErrors, DeleteByOrgByRepoResponses, DeleteByOrgByRepoWebhooksByWebhookIdData, DeleteByOrgByRepoWebhooksByWebhookIdErrors, DeleteByOrgByRepoWebhooksByWebhookIdResponses, GetByOrgApiKeysData, GetByOrgApiKeysErrors, GetByOrgApiKeysResponses, GetByOrgByRepoBranchesData, GetByOrgByRepoBranchesErrors, GetByOrgByRepoBranchesResponses, GetByOrgByRepoCommitsByShaData, GetByOrgByRepoCommitsByShaErrors, GetByOrgByRepoCommitsByShaResponses, GetByOrgByRepoCommitsData, GetByOrgByRepoCommitsErrors, GetByOrgByRepoCommitsResponses, GetByOrgByRepoContentData, GetByOrgByRepoContentErrors, GetByOrgByRepoContentResponses, GetByOrgByRepoData, GetByOrgByRepoErrors, GetByOrgByRepoResponses, GetByOrgByRepoWebhooksData, GetByOrgByRepoWebhooksErrors, GetByOrgByRepoWebhooksResponses, GetByOrgData, GetByOrgErrors, GetByOrgReposData, GetByOrgReposErrors, GetByOrgReposResponses, GetByOrgResponses, PatchByOrgByRepoData, PatchByOrgByRepoErrors, PatchByOrgByRepoResponses, PostByOrgApiKeysData, PostByOrgApiKeysErrors, PostByOrgApiKeysResponses, PostByOrgByRepoBranchesData, PostByOrgByRepoBranchesErrors, PostByOrgByRepoBranchesResponses, PostByOrgByRepoWebhooksData, PostByOrgByRepoWebhooksErrors, PostByOrgByRepoWebhooksResponses, PostByOrgReposData, PostByOrgReposErrors, PostByOrgReposResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List API keys
 *
 * List all API keys for the organization (key values are not returned)
 */
export const getByOrgApiKeys = <ThrowOnError extends boolean = false>(options: Options<GetByOrgApiKeysData, ThrowOnError>) => (options.client ?? client).get<GetByOrgApiKeysResponses, GetByOrgApiKeysErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/api-keys',
    ...options
});

/**
 * Create API key
 *
 * Create a new API key for programmatic access
 */
export const postByOrgApiKeys = <ThrowOnError extends boolean = false>(options: Options<PostByOrgApiKeysData, ThrowOnError>) => (options.client ?? client).post<PostByOrgApiKeysResponses, PostByOrgApiKeysErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/api-keys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke API key
 *
 * Revoke an API key by its ID
 */
export const deleteByOrgApiKeysById = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgApiKeysByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgApiKeysByIdResponses, DeleteByOrgApiKeysByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/api-keys/{id}',
    ...options
});

/**
 * List repositories
 *
 * List all repositories in the organization
 */
export const getByOrgRepos = <ThrowOnError extends boolean = false>(options: Options<GetByOrgReposData, ThrowOnError>) => (options.client ?? client).get<GetByOrgReposResponses, GetByOrgReposErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/repos',
    ...options
});

/**
 * Create repository
 *
 * Create a new repository in the organization
 */
export const postByOrgRepos = <ThrowOnError extends boolean = false>(options: Options<PostByOrgReposData, ThrowOnError>) => (options.client ?? client).post<PostByOrgReposResponses, PostByOrgReposErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/repos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete repository
 *
 * Permanently delete a repository and all its data
 */
export const deleteByOrgByRepo = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgByRepoData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgByRepoResponses, DeleteByOrgByRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}',
    ...options
});

/**
 * Get repository
 *
 * Get metadata for a specific repository
 */
export const getByOrgByRepo = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoResponses, GetByOrgByRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}',
    ...options
});

/**
 * Update repository
 *
 * Update repository name or upstream configuration
 */
export const patchByOrgByRepo = <ThrowOnError extends boolean = false>(options: Options<PatchByOrgByRepoData, ThrowOnError>) => (options.client ?? client).patch<PatchByOrgByRepoResponses, PatchByOrgByRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get content
 *
 * Get file content or directory listing at a path. Use Accept: application/json for the JSON union response, or Accept: application/octet-stream for raw file bytes. Directory + octet-stream requests return 406 Not Acceptable.
 */
export const getByOrgByRepoContent = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoContentData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoContentResponses, GetByOrgByRepoContentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/content',
    ...options
});

/**
 * List branches
 *
 * List all branches in a repository
 */
export const getByOrgByRepoBranches = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoBranchesData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoBranchesResponses, GetByOrgByRepoBranchesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/branches',
    ...options
});

/**
 * Create branch
 *
 * Create a new branch from an existing ref
 */
export const postByOrgByRepoBranches = <ThrowOnError extends boolean = false>(options: Options<PostByOrgByRepoBranchesData, ThrowOnError>) => (options.client ?? client).post<PostByOrgByRepoBranchesResponses, PostByOrgByRepoBranchesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/branches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete branch
 *
 * Delete a branch from a repository
 */
export const deleteByOrgByRepoBranchesByBranch = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgByRepoBranchesByBranchData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgByRepoBranchesByBranchResponses, DeleteByOrgByRepoBranchesByBranchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/branches/{branch}',
    ...options
});

/**
 * List commits
 *
 * List commits for a repository from a specific ref
 */
export const getByOrgByRepoCommits = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoCommitsData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoCommitsResponses, GetByOrgByRepoCommitsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/commits',
    ...options
});

/**
 * Get commit
 *
 * Retrieve a specific commit by its SHA
 */
export const getByOrgByRepoCommitsBySha = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoCommitsByShaData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoCommitsByShaResponses, GetByOrgByRepoCommitsByShaErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/commits/{sha}',
    ...options
});

/**
 * List webhooks
 *
 * List webhooks for a repository
 */
export const getByOrgByRepoWebhooks = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoWebhooksData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoWebhooksResponses, GetByOrgByRepoWebhooksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/webhooks',
    ...options
});

/**
 * Create webhook
 *
 * Create a webhook for a repository
 */
export const postByOrgByRepoWebhooks = <ThrowOnError extends boolean = false>(options: Options<PostByOrgByRepoWebhooksData, ThrowOnError>) => (options.client ?? client).post<PostByOrgByRepoWebhooksResponses, PostByOrgByRepoWebhooksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/webhooks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete webhook
 *
 * Delete a webhook from a repository
 */
export const deleteByOrgByRepoWebhooksByWebhookId = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgByRepoWebhooksByWebhookIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgByRepoWebhooksByWebhookIdResponses, DeleteByOrgByRepoWebhooksByWebhookIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/webhooks/{webhookId}',
    ...options
});

/**
 * Get organization
 *
 * Get organization metadata and repository counts
 */
export const getByOrg = <ThrowOnError extends boolean = false>(options: Options<GetByOrgData, ThrowOnError>) => (options.client ?? client).get<GetByOrgResponses, GetByOrgErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}',
    ...options
});
