// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteByOrgApiKeyByIdData, DeleteByOrgApiKeyByIdErrors, DeleteByOrgApiKeyByIdResponses, DeleteByOrgByRepoBranchByBranchData, DeleteByOrgByRepoBranchByBranchErrors, DeleteByOrgByRepoBranchByBranchResponses, DeleteByOrgByRepoData, DeleteByOrgByRepoErrors, DeleteByOrgByRepoResponses, DeleteByOrgByRepoWebhookByWebhookIdData, DeleteByOrgByRepoWebhookByWebhookIdErrors, DeleteByOrgByRepoWebhookByWebhookIdResponses, GetByOrgApiKeyData, GetByOrgApiKeyErrors, GetByOrgApiKeyResponses, GetByOrgByRepoBranchData, GetByOrgByRepoBranchErrors, GetByOrgByRepoBranchResponses, GetByOrgByRepoCommitByShaData, GetByOrgByRepoCommitByShaErrors, GetByOrgByRepoCommitByShaResponses, GetByOrgByRepoCommitData, GetByOrgByRepoCommitErrors, GetByOrgByRepoCommitResponses, GetByOrgByRepoContentData, GetByOrgByRepoContentErrors, GetByOrgByRepoContentResponses, GetByOrgByRepoData, GetByOrgByRepoDiffData, GetByOrgByRepoDiffErrors, GetByOrgByRepoDiffResponses, GetByOrgByRepoErrors, GetByOrgByRepoResponses, GetByOrgByRepoWebhookData, GetByOrgByRepoWebhookErrors, GetByOrgByRepoWebhookResponses, GetByOrgData, GetByOrgErrors, GetByOrgRepoData, GetByOrgRepoErrors, GetByOrgRepoResponses, GetByOrgRepoTagsData, GetByOrgRepoTagsErrors, GetByOrgRepoTagsResponses, GetByOrgResponses, GetWhoamiData, GetWhoamiErrors, GetWhoamiResponses, PatchByOrgByRepoData, PatchByOrgByRepoErrors, PatchByOrgByRepoResponses, PostByOrgApiKeyData, PostByOrgApiKeyErrors, PostByOrgApiKeyResponses, PostByOrgByRepoBranchData, PostByOrgByRepoBranchErrors, PostByOrgByRepoBranchResponses, PostByOrgByRepoCommitData, PostByOrgByRepoCommitErrors, PostByOrgByRepoCommitResponses, PostByOrgByRepoWebhookData, PostByOrgByRepoWebhookErrors, PostByOrgByRepoWebhookResponses, PostByOrgRepoBulkTagsData, PostByOrgRepoBulkTagsErrors, PostByOrgRepoBulkTagsResponses, PostByOrgRepoData, PostByOrgRepoErrors, PostByOrgRepoResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get caller identity
 *
 * Get the authenticated organization, effective scopes, and API key metadata
 */
export const getWhoami = <ThrowOnError extends boolean = false>(options?: Options<GetWhoamiData, ThrowOnError>) => (options?.client ?? client).get<GetWhoamiResponses, GetWhoamiErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/whoami',
    ...options
});

/**
 * List API keys
 *
 * List all API keys for the organization (key values are not returned)
 */
export const getByOrgApiKey = <ThrowOnError extends boolean = false>(options: Options<GetByOrgApiKeyData, ThrowOnError>) => (options.client ?? client).get<GetByOrgApiKeyResponses, GetByOrgApiKeyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/api-key',
    ...options
});

/**
 * Create API key
 *
 * Create a new API key for programmatic access
 */
export const postByOrgApiKey = <ThrowOnError extends boolean = false>(options: Options<PostByOrgApiKeyData, ThrowOnError>) => (options.client ?? client).post<PostByOrgApiKeyResponses, PostByOrgApiKeyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/api-key',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke API key
 *
 * Revoke an API key by its ID
 */
export const deleteByOrgApiKeyById = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgApiKeyByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgApiKeyByIdResponses, DeleteByOrgApiKeyByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/api-key/{id}',
    ...options
});

/**
 * List repositories
 *
 * List repositories in the organization using cursor pagination
 */
export const getByOrgRepo = <ThrowOnError extends boolean = false>(options: Options<GetByOrgRepoData, ThrowOnError>) => (options.client ?? client).get<GetByOrgRepoResponses, GetByOrgRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/repo',
    ...options
});

/**
 * Create repository
 *
 * Create a new repository in the organization
 */
export const postByOrgRepo = <ThrowOnError extends boolean = false>(options: Options<PostByOrgRepoData, ThrowOnError>) => (options.client ?? client).post<PostByOrgRepoResponses, PostByOrgRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/repo',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete repository
 *
 * Permanently delete a repository and all its data
 */
export const deleteByOrgByRepo = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgByRepoData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgByRepoResponses, DeleteByOrgByRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}',
    ...options
});

/**
 * Get repository
 *
 * Get metadata for a specific repository
 */
export const getByOrgByRepo = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoResponses, GetByOrgByRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}',
    ...options
});

/**
 * Update repository
 *
 * Update repository name, default branch, tags, or upstream configuration. Tags are patched: set values to add/update and null values to remove.
 */
export const patchByOrgByRepo = <ThrowOnError extends boolean = false>(options: Options<PatchByOrgByRepoData, ThrowOnError>) => (options.client ?? client).patch<PatchByOrgByRepoResponses, PatchByOrgByRepoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get repo Tags
 *
 * Get repository tag values and counts
 */
export const getByOrgRepoTags = <ThrowOnError extends boolean = false>(options: Options<GetByOrgRepoTagsData, ThrowOnError>) => (options.client ?? client).get<GetByOrgRepoTagsResponses, GetByOrgRepoTagsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/repo/tags',
    ...options
});

/**
 * Bulk update Tags
 *
 * Bulk set or remove repo tags
 */
export const postByOrgRepoBulkTags = <ThrowOnError extends boolean = false>(options: Options<PostByOrgRepoBulkTagsData, ThrowOnError>) => (options.client ?? client).post<PostByOrgRepoBulkTagsResponses, PostByOrgRepoBulkTagsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/repo/bulk/tags',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get content
 *
 * Get file content or directory listing at a path. Use Accept: application/json for the JSON union response, or Accept: application/octet-stream for raw file bytes. Directory + octet-stream requests return 406 Not Acceptable.
 */
export const getByOrgByRepoContent = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoContentData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoContentResponses, GetByOrgByRepoContentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/content',
    ...options
});

/**
 * List branches
 *
 * List all branches in a repository
 */
export const getByOrgByRepoBranch = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoBranchData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoBranchResponses, GetByOrgByRepoBranchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/branch',
    ...options
});

/**
 * Create branch
 *
 * Create a new branch from an existing ref
 */
export const postByOrgByRepoBranch = <ThrowOnError extends boolean = false>(options: Options<PostByOrgByRepoBranchData, ThrowOnError>) => (options.client ?? client).post<PostByOrgByRepoBranchResponses, PostByOrgByRepoBranchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/branch',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete branch
 *
 * Delete a branch from a repository
 */
export const deleteByOrgByRepoBranchByBranch = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgByRepoBranchByBranchData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgByRepoBranchByBranchResponses, DeleteByOrgByRepoBranchByBranchErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/branch/{branch}',
    ...options
});

/**
 * List commits
 *
 * List commits for a repository from a specific ref
 */
export const getByOrgByRepoCommit = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoCommitData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoCommitResponses, GetByOrgByRepoCommitErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/commit',
    ...options
});

/**
 * Create commit
 *
 * Create a new commit on a branch with file changes
 */
export const postByOrgByRepoCommit = <ThrowOnError extends boolean = false>(options: Options<PostByOrgByRepoCommitData, ThrowOnError>) => (options.client ?? client).post<PostByOrgByRepoCommitResponses, PostByOrgByRepoCommitErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/commit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get commit
 *
 * Retrieve a specific commit by its SHA
 */
export const getByOrgByRepoCommitBySha = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoCommitByShaData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoCommitByShaResponses, GetByOrgByRepoCommitByShaErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/commit/{sha}',
    ...options
});

/**
 * Get diff
 *
 * Retrieve the diff between two commit OIDs
 */
export const getByOrgByRepoDiff = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoDiffData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoDiffResponses, GetByOrgByRepoDiffErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/diff',
    ...options
});

/**
 * List webhooks
 *
 * List webhooks for a repository
 */
export const getByOrgByRepoWebhook = <ThrowOnError extends boolean = false>(options: Options<GetByOrgByRepoWebhookData, ThrowOnError>) => (options.client ?? client).get<GetByOrgByRepoWebhookResponses, GetByOrgByRepoWebhookErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/webhook',
    ...options
});

/**
 * Create webhook
 *
 * Create a webhook for a repository
 */
export const postByOrgByRepoWebhook = <ThrowOnError extends boolean = false>(options: Options<PostByOrgByRepoWebhookData, ThrowOnError>) => (options.client ?? client).post<PostByOrgByRepoWebhookResponses, PostByOrgByRepoWebhookErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/webhook',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete webhook
 *
 * Delete a webhook from a repository
 */
export const deleteByOrgByRepoWebhookByWebhookId = <ThrowOnError extends boolean = false>(options: Options<DeleteByOrgByRepoWebhookByWebhookIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteByOrgByRepoWebhookByWebhookIdResponses, DeleteByOrgByRepoWebhookByWebhookIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}/{repo}/webhook/{webhookId}',
    ...options
});

/**
 * Get organization
 *
 * Get organization metadata and repository counts
 */
export const getByOrg = <ThrowOnError extends boolean = false>(options: Options<GetByOrgData, ThrowOnError>) => (options.client ?? client).get<GetByOrgResponses, GetByOrgErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/{org}',
    ...options
});
