// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.mesa.dev/api/v1' | (string & {});
};

export type GetByOrgApiKeysData = {
    body?: never;
    path: {
        org: string;
    };
    query?: never;
    url: '/{org}/api-keys';
};

export type GetByOrgApiKeysErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgApiKeysError = GetByOrgApiKeysErrors[keyof GetByOrgApiKeysErrors];

export type GetByOrgApiKeysResponses = {
    /**
     * API keys list
     */
    200: {
        api_keys: Array<{
            id: string;
            name: string | null;
            scopes: Array<string>;
            last_used_at: string | null;
            expires_at: string | null;
            revoked_at: string | null;
            created_at: string;
        }>;
    };
};

export type GetByOrgApiKeysResponse = GetByOrgApiKeysResponses[keyof GetByOrgApiKeysResponses];

export type PostByOrgApiKeysData = {
    body: {
        name?: string;
        scopes?: Array<'git:read' | 'git:write' | 'repo:read' | 'repo:create' | 'repo:delete' | 'webhook:read' | 'webhook:write' | 'admin'>;
    };
    path: {
        org: string;
    };
    query?: never;
    url: '/{org}/api-keys';
};

export type PostByOrgApiKeysErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostByOrgApiKeysError = PostByOrgApiKeysErrors[keyof PostByOrgApiKeysErrors];

export type PostByOrgApiKeysResponses = {
    /**
     * API key created
     */
    201: {
        id: string;
        key: string;
        name: string | null;
        scopes: Array<string>;
        created_at: string;
    };
};

export type PostByOrgApiKeysResponse = PostByOrgApiKeysResponses[keyof PostByOrgApiKeysResponses];

export type DeleteByOrgApiKeysByIdData = {
    body?: never;
    path: {
        id: string;
        org: string;
    };
    query?: never;
    url: '/{org}/api-keys/{id}';
};

export type DeleteByOrgApiKeysByIdErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type DeleteByOrgApiKeysByIdError = DeleteByOrgApiKeysByIdErrors[keyof DeleteByOrgApiKeysByIdErrors];

export type DeleteByOrgApiKeysByIdResponses = {
    /**
     * API key revoked
     */
    200: {
        success: true;
    };
};

export type DeleteByOrgApiKeysByIdResponse = DeleteByOrgApiKeysByIdResponses[keyof DeleteByOrgApiKeysByIdResponses];

export type GetByOrgReposData = {
    body?: never;
    path: {
        org: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/{org}/repos';
};

export type GetByOrgReposErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgReposError = GetByOrgReposErrors[keyof GetByOrgReposErrors];

export type GetByOrgReposResponses = {
    /**
     * Repository list
     */
    200: {
        next_cursor: string | null;
        has_more: boolean;
        repos: Array<{
            id: string;
            org: string;
            name: string;
            default_branch: string;
            head_oid: string | null;
            size_bytes: number;
            created_at: string;
            /**
             * Optionally add an upstream repository. You can configure automatic syncing from the upstream repository.
             */
            upstream: {
                /**
                 * URL of the upstream repository
                 */
                uri: string;
                /**
                 * Automatic sync configuration, if enabled
                 */
                autosync: {
                    type: 'poll';
                    /**
                     * Polling period in seconds
                     */
                    period: number;
                    /**
                     * Conflict resolution strategy. "none" means sync will fail on conflicts.
                     */
                    resolution_strategy: 'none';
                } | null;
                /**
                 * Timestamp of the last sync attempt
                 */
                last_sync_attempt: string | null;
                /**
                 * Timestamp of the last successful sync
                 */
                last_sync_success: string | null;
                /**
                 * Error message from the last failed sync attempt
                 */
                last_sync_error: string | null;
                /**
                 * Whether this upstream has an authentication credential configured
                 */
                has_credential: boolean;
                /**
                 * The host the credential is scoped to (e.g. "github.com")
                 */
                credential_host: string | null;
            } | null;
        }>;
    };
};

export type GetByOrgReposResponse = GetByOrgReposResponses[keyof GetByOrgReposResponses];

export type PostByOrgReposData = {
    body: {
        name: string;
        default_branch?: string;
        upstream?: {
            /**
             * URL of the upstream repository
             */
            uri: string;
            /**
             * Optionally enable automatic sync from the upstream repository
             */
            autosync?: {
                type: 'poll';
                /**
                 * Polling period in seconds (60s to 24.8d)
                 */
                period: number;
                /**
                 * Conflict resolution strategy. "none" means sync will fail on conflicts.
                 */
                resolution_strategy?: 'none';
            };
            /**
             * Personal access token for private upstream repos. Set to null to unlink credential.
             */
            token?: string | null;
            /**
             * Username for git credential auth. Defaults to "x-access-token". Use actual username for Bitbucket app passwords.
             */
            token_username?: string;
        };
    };
    path: {
        org: string;
    };
    query?: never;
    url: '/{org}/repos';
};

export type PostByOrgReposErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostByOrgReposError = PostByOrgReposErrors[keyof PostByOrgReposErrors];

export type PostByOrgReposResponses = {
    /**
     * Repository created
     */
    201: {
        id: string;
        org: string;
        name: string;
        default_branch: string;
        head_oid: string | null;
        size_bytes: number;
        created_at: string;
        /**
         * Optionally add an upstream repository. You can configure automatic syncing from the upstream repository.
         */
        upstream: {
            /**
             * URL of the upstream repository
             */
            uri: string;
            /**
             * Automatic sync configuration, if enabled
             */
            autosync: {
                type: 'poll';
                /**
                 * Polling period in seconds
                 */
                period: number;
                /**
                 * Conflict resolution strategy. "none" means sync will fail on conflicts.
                 */
                resolution_strategy: 'none';
            } | null;
            /**
             * Timestamp of the last sync attempt
             */
            last_sync_attempt: string | null;
            /**
             * Timestamp of the last successful sync
             */
            last_sync_success: string | null;
            /**
             * Error message from the last failed sync attempt
             */
            last_sync_error: string | null;
            /**
             * Whether this upstream has an authentication credential configured
             */
            has_credential: boolean;
            /**
             * The host the credential is scoped to (e.g. "github.com")
             */
            credential_host: string | null;
        } | null;
    };
};

export type PostByOrgReposResponse = PostByOrgReposResponses[keyof PostByOrgReposResponses];

export type DeleteByOrgByRepoData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}';
};

export type DeleteByOrgByRepoErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type DeleteByOrgByRepoError = DeleteByOrgByRepoErrors[keyof DeleteByOrgByRepoErrors];

export type DeleteByOrgByRepoResponses = {
    /**
     * Repository deleted
     */
    200: {
        success: true;
    };
};

export type DeleteByOrgByRepoResponse = DeleteByOrgByRepoResponses[keyof DeleteByOrgByRepoResponses];

export type GetByOrgByRepoData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}';
};

export type GetByOrgByRepoErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoError = GetByOrgByRepoErrors[keyof GetByOrgByRepoErrors];

export type GetByOrgByRepoResponses = {
    /**
     * Repository
     */
    200: {
        id: string;
        org: string;
        name: string;
        default_branch: string;
        head_oid: string | null;
        size_bytes: number;
        created_at: string;
        /**
         * Optionally add an upstream repository. You can configure automatic syncing from the upstream repository.
         */
        upstream: {
            /**
             * URL of the upstream repository
             */
            uri: string;
            /**
             * Automatic sync configuration, if enabled
             */
            autosync: {
                type: 'poll';
                /**
                 * Polling period in seconds
                 */
                period: number;
                /**
                 * Conflict resolution strategy. "none" means sync will fail on conflicts.
                 */
                resolution_strategy: 'none';
            } | null;
            /**
             * Timestamp of the last sync attempt
             */
            last_sync_attempt: string | null;
            /**
             * Timestamp of the last successful sync
             */
            last_sync_success: string | null;
            /**
             * Error message from the last failed sync attempt
             */
            last_sync_error: string | null;
            /**
             * Whether this upstream has an authentication credential configured
             */
            has_credential: boolean;
            /**
             * The host the credential is scoped to (e.g. "github.com")
             */
            credential_host: string | null;
        } | null;
    };
};

export type GetByOrgByRepoResponse = GetByOrgByRepoResponses[keyof GetByOrgByRepoResponses];

export type PatchByOrgByRepoData = {
    body: {
        name?: string;
        default_branch?: string;
        upstream?: {
            /**
             * URL of the upstream repository
             */
            uri: string;
            /**
             * Optionally enable automatic sync from the upstream repository
             */
            autosync?: {
                type: 'poll';
                /**
                 * Polling period in seconds (60s to 24.8d)
                 */
                period: number;
                /**
                 * Conflict resolution strategy. "none" means sync will fail on conflicts.
                 */
                resolution_strategy?: 'none';
            };
            /**
             * Personal access token for private upstream repos. Set to null to unlink credential.
             */
            token?: string | null;
            /**
             * Username for git credential auth. Defaults to "x-access-token". Use actual username for Bitbucket app passwords.
             */
            token_username?: string;
        } | null;
    };
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}';
};

export type PatchByOrgByRepoErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PatchByOrgByRepoError = PatchByOrgByRepoErrors[keyof PatchByOrgByRepoErrors];

export type PatchByOrgByRepoResponses = {
    /**
     * Repository updated
     */
    200: {
        id: string;
        org: string;
        name: string;
        default_branch: string;
        head_oid: string | null;
        size_bytes: number;
        created_at: string;
        /**
         * Optionally add an upstream repository. You can configure automatic syncing from the upstream repository.
         */
        upstream: {
            /**
             * URL of the upstream repository
             */
            uri: string;
            /**
             * Automatic sync configuration, if enabled
             */
            autosync: {
                type: 'poll';
                /**
                 * Polling period in seconds
                 */
                period: number;
                /**
                 * Conflict resolution strategy. "none" means sync will fail on conflicts.
                 */
                resolution_strategy: 'none';
            } | null;
            /**
             * Timestamp of the last sync attempt
             */
            last_sync_attempt: string | null;
            /**
             * Timestamp of the last successful sync
             */
            last_sync_success: string | null;
            /**
             * Error message from the last failed sync attempt
             */
            last_sync_error: string | null;
            /**
             * Whether this upstream has an authentication credential configured
             */
            has_credential: boolean;
            /**
             * The host the credential is scoped to (e.g. "github.com")
             */
            credential_host: string | null;
        } | null;
    };
};

export type PatchByOrgByRepoResponse = PatchByOrgByRepoResponses[keyof PatchByOrgByRepoResponses];

export type GetByOrgByRepoContentData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query?: {
        oid?: string;
        path?: string;
        depth?: number;
    };
    url: '/{org}/{repo}/content';
};

export type GetByOrgByRepoContentErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoContentError = GetByOrgByRepoContentErrors[keyof GetByOrgByRepoContentErrors];

export type GetByOrgByRepoContentResponses = {
    /**
     * Content response
     */
    200: {
        type: 'file';
        name: string;
        path: string;
        sha: string;
        size: number;
        encoding: 'base64';
        content: string;
        mode: number;
    } | {
        type: 'symlink';
        name: string;
        path: string;
        sha: string;
        size: number;
        encoding: 'base64';
        content: string;
        mode: number;
    } | {
        type: 'dir';
        name: string;
        path: string;
        sha: string;
        child_count: number;
        entries: Array<{
            type: 'file';
            name: string;
            path: string;
            sha: string;
            size: number;
            mode: number;
        } | {
            type: 'symlink';
            name: string;
            path: string;
            sha: string;
            size: number;
            mode: number;
        } | {
            type: 'dir';
            name: string;
            path: string;
            sha: string;
        }>;
        next_cursor: string | null;
        has_more: boolean;
    };
};

export type GetByOrgByRepoContentResponse = GetByOrgByRepoContentResponses[keyof GetByOrgByRepoContentResponses];

export type GetByOrgByRepoBranchesData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/{org}/{repo}/branches';
};

export type GetByOrgByRepoBranchesErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoBranchesError = GetByOrgByRepoBranchesErrors[keyof GetByOrgByRepoBranchesErrors];

export type GetByOrgByRepoBranchesResponses = {
    /**
     * Branch list
     */
    200: {
        next_cursor: string | null;
        has_more: boolean;
        branches: Array<{
            name: string;
            head_oid: string;
            is_default: boolean;
        }>;
    };
};

export type GetByOrgByRepoBranchesResponse = GetByOrgByRepoBranchesResponses[keyof GetByOrgByRepoBranchesResponses];

export type PostByOrgByRepoBranchesData = {
    body: {
        name: string;
        from: string;
    };
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}/branches';
};

export type PostByOrgByRepoBranchesErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostByOrgByRepoBranchesError = PostByOrgByRepoBranchesErrors[keyof PostByOrgByRepoBranchesErrors];

export type PostByOrgByRepoBranchesResponses = {
    /**
     * Branch created
     */
    201: {
        name: string;
        head_oid: string;
        is_default: boolean;
    };
};

export type PostByOrgByRepoBranchesResponse = PostByOrgByRepoBranchesResponses[keyof PostByOrgByRepoBranchesResponses];

export type DeleteByOrgByRepoBranchesByBranchData = {
    body?: never;
    path: {
        org: string;
        repo: string;
        branch: string;
    };
    query?: never;
    url: '/{org}/{repo}/branches/{branch}';
};

export type DeleteByOrgByRepoBranchesByBranchErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type DeleteByOrgByRepoBranchesByBranchError = DeleteByOrgByRepoBranchesByBranchErrors[keyof DeleteByOrgByRepoBranchesByBranchErrors];

export type DeleteByOrgByRepoBranchesByBranchResponses = {
    /**
     * Branch deleted
     */
    200: {
        success: true;
    };
};

export type DeleteByOrgByRepoBranchesByBranchResponse = DeleteByOrgByRepoBranchesByBranchResponses[keyof DeleteByOrgByRepoBranchesByBranchResponses];

export type GetByOrgByRepoCommitsData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
        ref?: string;
    };
    url: '/{org}/{repo}/commits';
};

export type GetByOrgByRepoCommitsErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoCommitsError = GetByOrgByRepoCommitsErrors[keyof GetByOrgByRepoCommitsErrors];

export type GetByOrgByRepoCommitsResponses = {
    /**
     * Commit list
     */
    200: {
        next_cursor: string | null;
        has_more: boolean;
        commits: Array<{
            sha: string;
            message: string;
            author: {
                name: string;
                email: string;
                date?: string;
            };
            committer: {
                name: string;
                email: string;
                date?: string;
            };
        }>;
    };
};

export type GetByOrgByRepoCommitsResponse = GetByOrgByRepoCommitsResponses[keyof GetByOrgByRepoCommitsResponses];

export type PostByOrgByRepoCommitsData = {
    body: {
        branch: string;
        message: string;
        author: {
            name: string;
            email: string;
            date?: string;
        };
        committer?: {
            name: string;
            email: string;
            date?: string;
        };
        base_sha?: string;
        files: Array<{
            path: string;
            content: string;
            encoding?: 'utf-8' | 'base64';
            action?: 'upsert';
            mode?: '100644' | '100755';
        } | {
            path: string;
            action: 'delete';
        }>;
    };
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}/commits';
};

export type PostByOrgByRepoCommitsErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostByOrgByRepoCommitsError = PostByOrgByRepoCommitsErrors[keyof PostByOrgByRepoCommitsErrors];

export type PostByOrgByRepoCommitsResponses = {
    /**
     * Commit created
     */
    201: {
        sha: string;
        branch: string;
        message: string;
    };
};

export type PostByOrgByRepoCommitsResponse = PostByOrgByRepoCommitsResponses[keyof PostByOrgByRepoCommitsResponses];

export type GetByOrgByRepoCommitsByShaData = {
    body?: never;
    path: {
        org: string;
        repo: string;
        sha: string;
    };
    query?: never;
    url: '/{org}/{repo}/commits/{sha}';
};

export type GetByOrgByRepoCommitsByShaErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoCommitsByShaError = GetByOrgByRepoCommitsByShaErrors[keyof GetByOrgByRepoCommitsByShaErrors];

export type GetByOrgByRepoCommitsByShaResponses = {
    /**
     * Commit
     */
    200: {
        sha: string;
        message: string;
        author: {
            name: string;
            email: string;
            date?: string;
        };
        committer: {
            name: string;
            email: string;
            date?: string;
        };
    };
};

export type GetByOrgByRepoCommitsByShaResponse = GetByOrgByRepoCommitsByShaResponses[keyof GetByOrgByRepoCommitsByShaResponses];

export type GetByOrgByRepoDiffData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query: {
        base: string;
        head: string;
    };
    url: '/{org}/{repo}/diff';
};

export type GetByOrgByRepoDiffErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoDiffError = GetByOrgByRepoDiffErrors[keyof GetByOrgByRepoDiffErrors];

export type GetByOrgByRepoDiffResponses = {
    /**
     * Diff response
     */
    200: {
        base: string;
        head: string;
        truncated: boolean;
        stats: {
            files: number;
            additions: number;
            deletions: number;
            changes: number;
        };
        files: Array<{
            path: string;
            status: 'A' | 'M' | 'D' | 'R' | 'C' | 'T';
            old_path?: string;
            bytes?: number;
            is_eof?: boolean;
            raw?: string;
        }>;
        filtered_files: Array<{
            path: string;
            status: 'A' | 'M' | 'D' | 'R' | 'C' | 'T';
            old_path?: string;
            bytes?: number;
            is_eof?: boolean;
        }>;
    };
};

export type GetByOrgByRepoDiffResponse = GetByOrgByRepoDiffResponses[keyof GetByOrgByRepoDiffResponses];

export type GetByOrgByRepoWebhooksData = {
    body?: never;
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}/webhooks';
};

export type GetByOrgByRepoWebhooksErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgByRepoWebhooksError = GetByOrgByRepoWebhooksErrors[keyof GetByOrgByRepoWebhooksErrors];

export type GetByOrgByRepoWebhooksResponses = {
    /**
     * Webhook list
     */
    200: {
        webhooks: Array<{
            id: string;
            url: string;
            events: Array<'push'>;
            branches: Array<string> | null;
            globs: Array<string> | null;
            created_at: string;
            updated_at: string;
        }>;
    };
};

export type GetByOrgByRepoWebhooksResponse = GetByOrgByRepoWebhooksResponses[keyof GetByOrgByRepoWebhooksResponses];

export type PostByOrgByRepoWebhooksData = {
    body: {
        url: string;
        events?: Array<'push'>;
        branches?: Array<string>;
        globs?: Array<string>;
        secret?: string;
    };
    path: {
        org: string;
        repo: string;
    };
    query?: never;
    url: '/{org}/{repo}/webhooks';
};

export type PostByOrgByRepoWebhooksErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type PostByOrgByRepoWebhooksError = PostByOrgByRepoWebhooksErrors[keyof PostByOrgByRepoWebhooksErrors];

export type PostByOrgByRepoWebhooksResponses = {
    /**
     * Webhook created
     */
    201: {
        id: string;
        url: string;
        events: Array<'push'>;
        branches: Array<string> | null;
        globs: Array<string> | null;
        created_at: string;
        updated_at: string;
        secret: string;
    };
};

export type PostByOrgByRepoWebhooksResponse = PostByOrgByRepoWebhooksResponses[keyof PostByOrgByRepoWebhooksResponses];

export type DeleteByOrgByRepoWebhooksByWebhookIdData = {
    body?: never;
    path: {
        org: string;
        repo: string;
        webhookId: string;
    };
    query?: never;
    url: '/{org}/{repo}/webhooks/{webhookId}';
};

export type DeleteByOrgByRepoWebhooksByWebhookIdErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type DeleteByOrgByRepoWebhooksByWebhookIdError = DeleteByOrgByRepoWebhooksByWebhookIdErrors[keyof DeleteByOrgByRepoWebhooksByWebhookIdErrors];

export type DeleteByOrgByRepoWebhooksByWebhookIdResponses = {
    /**
     * Webhook deleted
     */
    200: {
        success: true;
    };
};

export type DeleteByOrgByRepoWebhooksByWebhookIdResponse = DeleteByOrgByRepoWebhooksByWebhookIdResponses[keyof DeleteByOrgByRepoWebhooksByWebhookIdResponses];

export type GetByOrgData = {
    body?: never;
    path: {
        org: string;
    };
    query?: never;
    url: '/{org}';
};

export type GetByOrgErrors = {
    /**
     * Invalid request
     */
    400: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Unauthorized
     */
    401: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Forbidden
     */
    403: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not found
     */
    404: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Not acceptable
     */
    406: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Conflict
     */
    409: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    /**
     * Internal error
     */
    500: {
        error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
};

export type GetByOrgError = GetByOrgErrors[keyof GetByOrgErrors];

export type GetByOrgResponses = {
    /**
     * Organization summary
     */
    200: {
        created_at: string;
        num_repos: number;
    };
};

export type GetByOrgResponse = GetByOrgResponses[keyof GetByOrgResponses];
